config/routes.rb
Rails.application.routes.draw do

  root to: "public/homes#top"
  get "home/about"=>"public/homes#about",as: "about"


  # 顧客登録,login
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # customers ★
  scope module: :public do
    resource :customers, only: [:show] do
    get 'information/edit' => 'customers#edit'
    patch 'information' => 'customers#update'
    get 'confirm'
    patch 'withdraw'=>'customers#withdraw'

      delete 'cart_items/destroy_all'
      resources :cart_items, only: [:index, :create, :update, :destroy]

    end

    resources :items, only: [:index, :show]

    # orders
    post 'orders/confirm'
    get 'orders/complete'
    resources :orders, only: [:new, :create, :show, :index]

    # deliveries
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]

  end

  # admin login~
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
   sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top'
  end

  # admin items
  namespace :admin do
    resources :items, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  end

  # admin genres
  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
  end

  # admin cutomers
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
  end

  # admin orders
  namespace :admin do
    resources :orders, only: [:index, :update, :show,]
  end

  # admon order_detail
  namespace :admin do
    resources :order_details, only: [:update]
  end









  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
  
  belongs_to :customer
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  has_one_attached :image
  
  def subtotal
    item.with_tax_price * amount
  end
  
  belongs_to :customer
  
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy

  has_many :orders, dependent: :destroy

  has_many :addresses, dependent: :destroy

  def full_name
    last_name + first_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  belongs_to :genre
  
  has_many :cart_items, dependent: :destroy
  
  has_many :order_details, dependent: :destroy

  def with_tax_price
    (price * 1.10).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord
  has_one_attached :image
  
  belongs_to :customer
  
  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { wait: 0, confirmation: 1, production: 2, shipping: 3, finish: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  
  enum production_status: {cant: 0, wait: 1, production:2, finish:3}
  
  belongs_to :order
  
  belongs_to :item
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).per(10)
    @quantity = 0
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new
    @item=Item.new
  end

  def create
    @item=Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end

  end

  def index
    @items=Item.page(params[:page]).per(10)
  end

  def show
    @item=Item.where(id: params[:id])
  end

  def edit
    @item=Item.find(params[:id])
  end

  def update
    @item=Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_items_path
    else
      render :edit
    end
  end

  def destroy
    @item=Item.find(params[:id])
    @item.destroy
  end

  private

  def item_params
    params.require(:item).permit(:name, :image, :introduction, :genre_id, :price, :is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def full_name
    $full_name = (current_customer.last_name + current_customer.first_name)
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/addresses_helper.rb
module Admin::AddressesHelper
end

app/helpers/admin/cart_items_helper.rb
module Admin::CartItemsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/homes/top.html.erb
<h4 class="pl-5 ml-5">注文履歴一覧</h4>
<div class="container">
  <div class="row">
    <div class="col-12">
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th>購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>
        <% @orders.each do |order| %>
          <tbody>
            <tr>
              <td><u><%= link_to order.created_at.strftime('%Y/%m/%d %H:%M:%S'), admin_order_path(order.id), class: "text-dark" %></u></td>
              <td><%= order.customer.full_name %></td>
                  <% order.order_details.each do |order_detail| %>
                    <% @quantity += order_detail.quantity %>
                  <% end %>
              <td>    
                <%= @quantity %>
              </td>
              <td><%= order.status_i18n %></td>
            </tr>
          </tbody>
          <% @quantity = 0 %>
        <% end %>
      </table>
    </div>
  </div>
</div>
<div class="d-flex justify-content-center">
  <%= paginate @orders %>
</div>

app/views/admin/items/edit.html.erb
<h4>商品編集</h4>
<div class="container">
  <div class="row">
    <div class="col-10">
      <%= form_with model: @item, url: admin_item_path(params[:id]) do |f| %>
        <table>
          <tr>
            <th><%= f.label :image, "商品画像" %></th>
            <td><%= f.file_field :image, accept: "image/*" %></td>
          </tr>
          <tr>
            <th><%= f.label :name, "商品名" %></th>
            <td><%= f.text_field :name %></td>
          </tr>
          <tr>
            <th><%= f.label :introduction, "商品説明" %></th>
            <td><%= f.text_area :introduction %></td>
          </tr>
          <tr>
            <th><%= f.label :genre_id, "ジャンル" %></th>
            <td><%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name), { include_blank: '-- 選択してください --'} %></td>
          </tr>
          <tr>
            <th><%= f.label :price, "税抜価格" %></th>
            <td><%= f.text_field :price %></td>
          </tr>
          <tr>
            <th>販売ステータス</th>
            <td class="h5"><%= f.radio_button :is_active, true, id: "item_販売中" %><%= f.label "販売中" %>
                <%= f.radio_button :is_active, false, id: "item_販売停止中" %><%= f.label "販売停止中" %></td>
          </tr>
          <tr>
            <th><%= f.submit "変更を保存", class: "btn btn-success px-4" %></th>
          </tr>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <h4 class="col-10">商品一覧</h4>
    <button class=" btn btn-light rounded-circle shadow-sm bg-white rounded">
      <h4>
        <%= link_to "＋", new_admin_item_path, class: "text-secondary" %>
      </h4>
    </button>
  </div>
  <div class="row mt-4">
      <table class="table table-borderless col-12">
        <thead class="thead-light">
          <tr>
            <th class="mx-auto">商品ID</th>
            <th class="mx-auto">商品名</th>
            <th class="mx-auto">税抜価格</th>
            <th class="mx-auto">ジャンル</th>
            <th class="mx-auto">ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
            <tr>
              <td><%= item.id %></td>
              <td><u><%=link_to item.name, admin_item_path(item.id), class: "text-dark" %></u></td>
              <td><%= item.price.to_s(:delimited) %></td>
              <td><%= item.genre.name %></td>
              <% if item.is_active %>
                <td class="text-success">販売中</td>
              <% else %>
                <td class="text-secondary fw-bold">販売停止中</td>
              <% end %>
            </tr>
            <!--delete-->
           
          <% end %>
        </tbody>
      </table>
      <div class="d-flex justify-content-center">
        <%= paginate @items %>
      </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<h4>商品新規登録</h4>
<div class="container">
  <div class="row">
    <div class="col-11">
      <%=form_with model: @item, url: admin_items_path do |f| %>
        <table>
          <tr>
            <th><%=f.label :image, "商品画像" %></th>
            <td><%=f.file_field :image, accept: "image/*" %></td>
          </tr>
          <tr>
            <th><%=f.label :name, "商品名" %></th>
            <td><%=f.text_field :name %></td>
          </tr>
          <tr>
            <th><%=f.label :introduction, "商品説明" %></th>
            <td><%=f.text_area :introduction%></td>
          </tr>
          <tr>
            <th><%=f.label :genre_id, "ジャンル" %></th>
            <td><%=f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name), { include_blank: '-- 選択してください --'}%></td
          ></tr>
          <tr>
            <th><%=f.label :price, "税抜価格" %></th>
            <td><%=f.text_field :price %>円</td>
          </tr>
          <tr>
            <th>販売ステータス</th>
            <td><%=f.radio_button :is_active, "販売中", id: "item_is_active" %><%=f.label :is_active, "販売中" %>
              <%=f.radio_button :is_active, "販売停止中", id: "item_is_not_active"%><%=f.label :is_not_active, "販売停止中" %></td>
          </tr>
          <tr>
            <th><%= f.submit "新規登録", class: "btn btn-success px-4" %></th>
          </tr>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<h4>商品詳細</h4>
<div class="container">
  <div class="row">
    <% @item.each do |item| %>
      <div class="ml-auto mr-5">
        <%= image_tag item.image, size: "300x200" %>
      </div>
      <table class="mr-auto">
        <tr>
          <th>商品名</th>
          <td><%= item.name %></td>
        </tr>
        <tr>
          <th>商品説明</th>
          <td><%= item.introduction %></td>
        </tr>
        <tr>
          <th>ジャンル</th>
          <td><%= item.genre.name %></td>
        </tr>
        <tr>
          <th>税込価格<br>(税抜価格)</th>
          <td><%= item.price.to_s(:delimited) %> (<%= item.with_tax_price.to_s(:delimited) %>) 円</td>
        </tr>
        <tr>
          <th>販売ステータス</th>
          <% if item.is_active%>
            <td class="text-success">販売中</td>
          <% else %>
            <td class="text-secondary">販売停止中</td>
          <% end %>
          
        </tr>
      </table>
    <% end %>
  </div>
  <div class="row">
    <div class="col text-center mt-5">
      <%= link_to "編集する",edit_admin_item_path(params[:id]), class: "py-2 px-5 btn btn-success" %>
    </div>
  </div>
</div>