config/routes.rb
Rails.application.routes.draw do

  root to: "public/homes#top"
  get "home/about"=>"public/homes#about",as: "about"


  # 顧客登録,login
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # customers ★
  scope module: :public do
    resource :customers, only: [:show] do
    get 'information/edit' => 'customers#edit'
    patch 'information' => 'customers#update'
    get 'confirm'
    patch 'withdraw'=>'customers#withdraw'

      delete 'cart_items/destroy_all'
      resources :cart_items, only: [:index, :create, :update, :destroy]

    end

    resources :items, only: [:index, :show]

    # orders
    post 'orders/confirm'
    get 'orders/complete'
    resources :orders, only: [:new, :create, :show, :index]

    # deliveries
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]

  end

  # admin login~
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
   sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top'
  end

  # admin items
  namespace :admin do
    resources :items, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  end

  # admin genres
  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
  end

  # admin cutomers
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
  end

  # admin orders
  namespace :admin do
    resources :orders, only: [:index, :update, :show,]
  end

  # admon order_detail
  namespace :admin do
    resources :order_details, only: [:update]
  end









  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
  
  belongs_to :customer
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  has_one_attached :image
  
  def subtotal
    item.with_tax_price * amount
  end
  
  belongs_to :customer
  
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy

  has_many :orders, dependent: :destroy

  has_many :addresses, dependent: :destroy

  def full_name
    last_name + first_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  belongs_to :genre
  
  has_many :cart_items, dependent: :destroy
  
  has_many :order_details, dependent: :destroy

  def with_tax_price
    (price * 1.10).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord
  has_one_attached :image
  
  belongs_to :customer
  
  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { wait: 0, confirmation: 1, production: 2, shipping: 3, finish: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  
  enum production_status: {cant: 0, wait: 1, production:2, finish:3}
  
  belongs_to :order
  
  belongs_to :item
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def full_name
    $full_name = (current_customer.last_name + current_customer.first_name)
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/addresses_helper.rb
module Admin::AddressesHelper
end

app/helpers/admin/cart_items_helper.rb
module Admin::CartItemsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/headers/_admin_header.html.erb
              <li>
                <%=link_to "商品一覧", admin_items_path,class: "btn btn-outline-secondary mr-3" %>
              </li>
              <li>
                <%=link_to "会員一覧", admin_customers_path,class: "btn btn-outline-secondary mr-3" %>
              </li>
              <li>
                <%=link_to "注文履歴一覧", admin_root_path,class: "btn btn-outline-secondary mr-3" %>
              </li>
              <li>
                <%=link_to "ジャンル一覧", admin_genres_path,class: "btn btn-outline-secondary mr-3" %>
              </li>
              <li>
                <%=link_to "ログアウト", destroy_admin_session_path,class: "btn btn-outline-secondary mr-3",method: :delete %>
              </li>

app/views/headers/_customer_header.html.erb
              <p>ようこそ、<%= current_customer.last_name %>さん！</p>
              <li>
                <%=link_to "マイページ", customers_path,class: "btn btn-outline-secondary mr-3" %>
              </li>
              <li>
                <%=link_to "商品一覧", items_path,class: "btn btn-outline-secondary mr-3" %>
              </li>
              <li>
                <%=link_to "カート", customers_cart_items_path,class: "btn btn-outline-secondary mr-3" %>
              </li>
              <li>
                <%=link_to "ログアウト", destroy_customer_session_path,class: "btn btn-outline-secondary mr-3",method: :delete %>
              </li>

app/views/headers/_logout_header.html.erb
              <li>
                <%=link_to "About",about_path,class: "btn btn-outline-secondary mr-3 px-4" %>
              </li>
              <li>
                <%=link_to "商品一覧",items_path,class: "btn btn-outline-secondary mr-3" %>
              </li>
              <li>
                <%=link_to "新規登録",new_customer_registration_path,class: "btn btn-outline-secondary mr-3" %>
              </li>
              <li>
                <%=link_to "ログイン",new_customer_session_path,class: "btn btn-outline-secondary mr-3" %>
              </li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <!---->
    
    <!---->
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!---->
    
    <!---->
  </head>

  <body>
    <header class="mb-5">
      <nav class="navbar navbar-expand-lg navbar-light bg-light py-5">
        <% if admin_signed_in? %>
          <a class="navbar-brand border border-secondary px-4" href="/admin">
            <h2>Nagano Cake</h2>
          </a>
        <% else %>
          <a class="navbar-brand border border-secondary px-4" href="/">
            <h2>Nagano Cake</h2>
          </a>
        <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <% if admin_signed_in? %>
              <%= render "headers/admin_header" %>
            <% elsif customer_signed_in? %>
              <%= render "headers/customer_header" %>
            <% else %>
              <%= render "headers/logout_header" %>
            <% end %>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input type="text" class="form-control" placeholder="Search">
            <button class="btn btn-outline-success" type="button" id="button-addon2"><i class="fas fa-search"></i></button>
          </form>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
  <footer class="bg-light py-5 mt-5">
    <div class="mx-auto mt-3">
      <p class="text-center">Nagano Cake</p>
    </div>
  </footer>
</html>